[phases.setup]
nixPkgs = ["nodejs_20", "python311"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["python3 -m ensurepip --upgrade && python3 -m pip install pandas scikit-learn numpy joblib"]

[start]
cmd = "node backend/server.js"
