FROM node:18

RUN apt-get update && apt-get install -y python3 python3-pip

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN pip3 install pandas scikit-learn numpy --break-system-packages

EXPOSE 3000

CMD ["node", "server.js"]
